### ISSUE TITLE
Simulate a question

### ISSUE THREAD

**Issue by GiovaneRobertiTafine** [FernandoAcTr/react-form-ease#2]
I'm trying to simulate the use of the lib on some platforms, but I have problems using it.

Stackblitz:

> The` entrypoint for 'react-form-ease' could not successfully be resolved. The file '/turbo_modules/react-form-ease@1.2.0/dist/index.umd.js' does not exist. Please log an issue with the package author or check for an updated version of the package.

Codesandbox

> Object.useState
https://k3gd77.csb.app/node_modules/react/18.2.0/cjs/react.development.js:1622:21
Ye
https://k3gd77.csb.app/node_modules/react-form-ease/dist/index.umd.cjs:27:3324
App
/src/App.tsx:5:31

**Comment by FernandoAcTr** [comment]
@GiovaneRobertiTafine Thanks for your contrib, there is a PR fixind this issue and a new version of the lib 1.2.1 with a minor fix. You can check the use of this lib in this [stackblitz example](https://stackblitz.com/edit/stackblitz-starters-7i2aih?file=src%2FApp.js)
